### ISSUE TITLE
Proven approaches and recipes for most popular CI systems

### ISSUE THREAD

**Issue by distorhead** [werf/werf#1617]
* GitLab CI support has been implemented a while ago (and recently updated via #2391, #2416, etc.). The ready-to-use guide is published in [documentation](https://werf.io/documentation/guides/gitlab_ci_cd_integration.html).
* GitHub Actions support has been recently implemented in #2210. The guide is [here](https://werf.io/documentation/guides/github_ci_cd_integration.html).
* An issue for Jenkins & TeamCity is #1150.
* [Here is a general overview](https://werf.io/documentation/guides/generic_ci_cd_integration.html) of how you can integrate werf with other CI systems.

**Comment by shurup** [comment]
* GitLab CI support has been implemented a while ago (and recently updated via #2391, #2416, etc.). The ready-to-use guide is published in [documentation](https://werf.io/documentation/guides/gitlab_ci_cd_integration.html).
* GitHub Actions support has been recently implemented in #2210. The guide is [here](https://werf.io/documentation/guides/github_ci_cd_integration.html).
* An issue for Jenkins & TeamCity is #1150.
* [Here is a general overview](https://werf.io/documentation/guides/unsupported_ci_cd_integration.html) of how you can integrate werf with other CI systems.

**Comment by distorhead** [comment]
We have decided, that a good general instruction about embedding werf into any CI/CD system is enough. We tried to write such instructions:

 1. https://werf.io/documentation/using_with_ci_cd_systems.html
 2. https://werf.io/documentation/advanced/ci_cd/generic_ci_cd_integration.html
 3. https://werf.io/documentation/internals/how_ci_cd_integration_works/general_overview.html
