### ISSUE TITLE
[werf.yaml] OpenAPI specification for configVersion 2.0

### ISSUE THREAD

**Issue by alexey-igrychev** [werf/werf#1777]
Rework werf.yaml, use OpenAPI specification to generate config parser.

**Comment by diafour** [comment]
The easiest option, for now, is to unmarshal config into `map[string]interface{}`, validate this object against Schema and than Unmarshal config into typed objects.

https://github.com/flant/shell-operator/blob/0a045385ab30900b52929530fd682c01e1678382/pkg/hook/hook_config.go#L125-L153

**Comment by alexey-igrychev** [comment]
rejected
