### ISSUE TITLE
Ability to annotate and label a namespace

### ISSUE THREAD

**Issue by distorhead** [werf/werf#1936]
- Auto werf annotations: `project.werf.io/env`, `project.werf.io/name`, `project.werf.io/env`.
 - Annotations added by `--add-annotation` flag.
 - Labels added by `--add-label` flag.

Open question: how to deal with namespaces hardcoded in the templates?

**Comment by viperx77** [comment]
Is there any way to accomplish this yet? I need my namespace labeled for istio-injection

**Comment by viperx77** [comment]
No progress?

**Comment by ilya-lesikov** [comment]
Currently if you need to add some labels/annotations to the release namespace the easiest way is to `kubectl label/annotate myns ...` after `werf converge`.

Alternatively, you can do `kubectl create ns myns` yourself, then `kubectl label/annotate`, then `werf converge`.

Duplicate of #4195.
