### ISSUE TITLE
Review English documentation

### ISSUE THREAD

**Issue by kirkonru** [werf/werf#2049]
On the basis of [Review Russian documentation #1963](https://github.com/flant/werf/issues/1963)

- [x]  Main
- [x]  Releases
- [x]  README
- [x]  Documentation Overview
- [x]  Configuration / Introduction
- [x]  Configuration / Dockerfile image
- [x]  Configuration / Stapel Image / Naming
- [x]  Configuration / Stapel Image / Base Image
- [x]  Configuration / Stapel Image / Docker directive
- [x]  Configuration / Stapel Image / Git directive
- [x]  Configuration / Stapel Image / Assembly Instructions
- [x]  Configuration / Stapel Image / Mounts
- [ ]  Configuration / Stapel Image / Imports
- [ ]  Configuration / Stapel Artifact
- [ ]  Configuration / Deploy into Kubernetes
- [ ]  Configuration / Cleanup
- [x]  Reference / Stages and Images
- [x]  Reference / Build Process
- [x]  Reference / Publish Process
- [x]  Reference / Deploy Process / Deploy into Kubernetes
- [ ]  Reference / Deploy Process / Working with secrets
- [ ]  Reference / Deploy Process / Working with chart dependencies
- [ ]  Reference / Deploy Process / Differences with helm
- [ ]  Reference / Deploy Process / Resources update methods and adoption
- [ ]  Reference / Cleaning Process
- [ ]  Reference / Working with Docker registries
- [x]  Reference / CI/CD workflows overview
- [x]  Reference / Plugging into CI/CD/ Overview
- [x]  Reference / Plugging into CI/CD/ GitLab CI
- [ ]  Reference / Development and debug / Setup minikube
- [ ]  Reference / Development and debug / Stage introspection
- [ ]  Reference / Development and debug / As layers
- [ ]  Reference / Development and debug / Lint and render chart
- [x]  Reference / Toolbox / Slug
- [x]  Reference / Toolbox / SSH
- [x]  Reference / Guides / Installation
- [ ]  Reference / Guides / Getting started
- [ ]  Reference / Guides / Deploy into kubernetes
- [x]  Reference / Guides / GitLab CICD integration
- [x]  Reference / Guides / GitHub CICD integration
- [ ]  Reference / Guides / Unsupported CICD integration
- [ ]  Reference / Guides / Advanced build / First application
- [ ]  Reference / Guides / Advanced build / Multi images
- [ ]  Reference / Guides / Advanced build / Mounts
- [ ]  Reference / Guides / Advanced build / Artifacts
- [x]  Development / Stapel

**Comment by alexey-igrychev** [comment]
outdated
