### ISSUE TITLE
Не удаляются /tmp/dapp-DATE-random директории

### ISSUE THREAD

**Issue by distorhead** [werf/werf#209]
Для начала надо воспроизвести. Были жалобы на 0.7.27 и 0.10.3.

**Comment by alexey-igrychev** [comment]
Удаление кеша происходит после сборки следующей командой `FileUtils.rm_rf(tmp_path)`.
Если в кеше присутсвуют директории, для удаление которых недостаточно прав (пользователю запустившиму dapp), то **команда не выполнит удаление кеша и не упадёт с ошибкой**. Такая ситуация может возникать во временных директориях mount-ов, которые монтируются в контейнеры при сборке и могут содержать файлы произвольных пользователей.

**Comment by diafour** [comment]
Can we close this?  https://github.com/flant/dapp/pull/557
