### ISSUE TITLE
Allow use artifact images for werf run

### ISSUE THREAD

**Issue by drdeimos** [werf/werf#2112]
Have two images: artifact (build npm static) && nginx (distribute statice over web).
_Sometimes_ we need run command (npm update/publish package) in _builded_ artifact image, but `werf run` allow only image name as argument for run command.
Possible to make `werf run` allow to run command in artifact image?

**Comment by ilya-lesikov** [comment]
We are planning to deprecate artifacts, so we recommend to use images instead of artifacts (although there are few features missing at the moment). If you can switch from artifacts to images, then you can use `werf run` on them.
