### ISSUE TITLE
Resources with random names are not cleaned up during release upgrades

### ISSUE THREAD

**Issue by distorhead** [werf/werf#2144]
Resources such as Job-s with random names (used for database migrations for example) should be cleaned up during next release updates. This cleanup occurs in helm kube-client: delete resources from old release revision that are not present in the current version of the chart. Cleanup works as long as deployed resource has reached ready state successfully, but in the case of resource runtime failure this resource will stay in the cluster forever, because this resource belongs to the failed release revision.

Possible solution: do separate cleanup for the release revisions that are in the PENDING_UPGRADE or FAILED state.

**Comment by ilya-lesikov** [comment]
Solved. Unless the Job is a hook, then there are [hook-delete-policies](https://helm.sh/docs/topics/charts_hooks/#hook-deletion-policies) in play, but this is as expected.
