### ISSUE TITLE
Werf cleanup only for specified images

### ISSUE THREAD

**Issue by distorhead** [werf/werf#2166]
Add ability to specify concrete image or set of images from werf.yaml for commands: `werf images cleanup`, `werf stages cleanup` and `werf cleanup`.

**Comment by alexey-igrychev** [comment]
There has been no user request for this feature, and addressing it is complex because application images may share layers that need to be considered during cleanup. Existing cleanup policies allow for flexible configuration to meet any needs (https://werf.io/docs/v2/usage/cleanup/cr_cleanup.html).
