### ISSUE TITLE
New unified werf cleanup procedure

### ISSUE THREAD

**Issue by distorhead** [werf/werf#2212]
Implement new unified cleanup algorithm for all tagging strategies.

 - Keep no more than N images related with N last commits for all git heads.
 - Keep no more than N stages related with N last commits for all git heads.
 - Keep all images that are being used in the Kubernetes.
 - Keep all images that are recorded in the Helm release manifests.
 - Stage can be cleared if it is not related with no HEAD and it is not used in Kubernetes and Helm.

![image](https://user-images.githubusercontent.com/1161992/76341032-824c8900-630d-11ea-8bf3-e42f7e02a9fd.png)

**Comment by distol** [comment]
Crazy drawings in Russian ))). As the author of them, I apologize. We are doing our best to make the design and decision making process public, but as we are a small team it sometimes seems easier to implement and than to document it, rather than going the right way. Sorry about that.
