### ISSUE TITLE
Werf deploy into chart repo

### ISSUE THREAD

**Issue by distorhead** [werf/werf#2214]
There should be an ability to deploy werf chart into chart repo with `werf deploy-into-chart`. And then deploy a chart from chart-repo. Then it will be possible to make independent releases of multiple microservices stored in different repos.

**Comment by ilya-lesikov** [comment]
Now we have bundles that are basically Helm charts, but with values that are set from cli, user annotations/labels and built images information embedded into them. You can publish multiple bundles into OCI registry and then deploy them separately, whenever you want.
