### ISSUE TITLE
werf tag command

### ISSUE THREAD

**Issue by distorhead** [werf/werf#2230]
Need more use cases from real users in this issue before implementing this command.
Maybe implement lowlevel command `werf images tag`.

**Comment by distorhead** [comment]
+ 1 real case: test images before publishing using docker compose.

**Comment by rayderua** [comment]
Привет.
Правильно ли я понял задумку, это будет возможность протегировать образы локально до их публикации?
т.е. не городить костыли типа этого (умнее пока не придумал):
```
for IMAGE in $(grep '^image:' werf.yaml | cut -d' ' -f2); do
  LOCAL=$(werf --stages-storage :local run ${IMAGE} --dry-run --bash=false  | grep '^docer run' | grep -oE 'werf-stages-storage/\w+:\w+-\w+')
  docker tag  ${LOCAL} ${IMAGE}:local
done
```
?
Мне вот очень не хватает этого функционала, в основном как раз для тестов

**Comment by rayderua** [comment]
@distorhead

**Comment by distorhead** [comment]
Привет! Сейчас идёт работа над v1.2, там задумана команда werf-export, которая будет своего рода аналогом docker-tag: https://github.com/werf/werf/issues/2868
