### ISSUE TITLE
Update ansible in stapel

### ISSUE THREAD

**Issue by distorhead** [werf/werf#2234]
- Build newest ansible in the stapel image.
 - Build python 3 for the newest ansible in the stapel image.
 - Make switch for the user to select old ansible or new ansible.
 - Keep ansible 2.7 by default.

Also, as ansible and python is being updated, make sure following problems are fixed:
 - repair apt-key module;
 - yum in centos 8 should be fixed;
 - ansible file name too long problem;
 - some other ansible-related problems: https://github.com/flant/werf/labels/ansible.
 -

**Comment by alexey-igrychev** [comment]
This issue is being closed because the ansible functionality is no longer being developed or supported. This feature has been deprecated and will be removed in version v3. We recommend using the shell directive instead.
