### ISSUE TITLE
WARNING: stage setup dependency path src/ have not been found in own git

### ISSUE THREAD

**Issue by distorhead** [werf/werf#2258]
This config:

```
  stageDependencies:
    setup:
    - src/
```

gives `WARNING: stage setup dependency path src/ have not been found in own git`.

While the following Config does not give any warnings:

```
  stageDependencies:
    setup:
    - src/**
```

Check that directory specification in v1.1 is working.

**Comment by distorhead** [comment]
_Update_

Directory specification is working in v1.1 only without trailing slash.

**Comment by alexey-igrychev** [comment]
fixed
