### ISSUE TITLE
No ability to clear out resources after werf.io/set-resource-only-on-creation removed

### ISSUE THREAD

**Issue by distorhead** [werf/werf#2426]
The case:
 - werf.io/set-resources-only-on-creation was defined in the resource;
 - VPA has set some resource limits for the resource in the kubernetes;
 - user deletes werf.io/set-resources-only-on-creation annotation and redeploys an app.
 - werf does not clear resource limits that has been set by VPA.

Maybe werf should automatically clear resource limits in such case? For now it should be possible to delete limits by setting `spec.containers[].resources=null` explicitly in the templates, or by editing resource manually.

Take into account that resource without limits is always potentially dangerous.

**Comment by ilya-lesikov** [comment]
There is no such feature as `werf.io/set-resources-only-on-creation` anymore.
