### ISSUE TITLE
Consistency check of published images takes too long

### ISSUE THREAD

**Issue by distorhead** [werf/werf#2455]
When building an image that published with `stages-signature` (content-based) tagging signature it is unnecessary to check parent docker-image-id of already published image to decide: whether werf should republish this image because of changed docker-image-id. This check consumes too much time. Example of such check:

```
│ Fetching existing repo tags ... (0.18 seconds)
│ │ Getting existing tag 4cbfc5758598aa28b28a3c1c02435de6a6619e5d01876074eb ... (0.47 seconds)
│ └ stages-signature tagging strategy (0.47 seconds)
```

Compatibility mode should be implemented to perform such check when `tag-or-branch` or another custom tagging strategy used.

**Comment by distorhead** [comment]
Performance issue fixed by the https://github.com/flant/werf/pull/2456.

Maybe there should be an option to force check by docker-image-ID even for `stages-signature` content-based tags. So this issue should be opened for now.

**Comment by distorhead** [comment]
https://github.com/flant/werf/issues/2454#issuecomment-636953251

**Comment by alexey-igrychev** [comment]
We have refused this check
