### ISSUE TITLE
Хранение содержимого KUBECONFIG в переменных окружения

### ISSUE THREAD

**Issue by tuchinsky** [werf/werf#2545]
Кейс такой - сейчас у юзера на раннере который запускает werf в `.kube/config` лежит конфиг под все контексты кластеров в которые необходимо деплоить. Любой разработчик может взять репозиторий в которой уже есть деплой в прод, сделать в нем бранч и поменять `.gitlab-ci.yml` таким образом, что бы с его ветки катилось в продовый контекст. Если добавить содержимое `.kube/config` в переменную, то ее можно будет сделать protected и она будет доступна только для protected бранчей. Это не должно повлиять на cleanup, т.к. он почти всегда запускается с master бранча

**Comment by distorhead** [comment]
Werf could accept base64 of yaml-config:

```
cat ~/.kube/config | base64 -w0
```

with parameter `--kube-config-base64-data`.

The same param has been implemented for github-actions for werf: https://github.com/werf/actions#kubeconfig-setup-optional . It will be useful for all users to implement such param in the werf itself.
