### ISSUE TITLE
Render does not perform linting but performs yaml validation

### ISSUE THREAD

**Issue by distorhead** [werf/werf#2600]
We have render and lint commands. Render evaluates go-templates and then performs yaml-validation. Lint command validates yaml to confirm with kubernetes resource description rules.

This arrangement of commands has some problems:
 - Why render validates yaml? As a templates writer I want to have ability to render templates without yaml-validation to check some go-templates constructions and generated text output.
 - If render validates yaml, then why render does not perform lint automatically? As a templates writer I want to have a single command to check everything alright and separated render and lint commands seems like overloaded cli interface, because user can forget to call lint after successful render (with successful yaml validation) and this user will receive unwanted stupid error in deploy process, just because he forgot to call lint.

Solution:
 - Lint command should perform yaml-validation and kubernetes resource manifests checks.
 - Render command should perform not only yaml-validation, but also kubernetes resource manifests checks — lint.
 - Render by default should print raw render result immediately after evaluating of go-templates, before any validations. This way user have an ability to debug some arbitrary go-templates constructions without thinking about yaml correctness.
 - Render should have an option to disable any validations and lint and only print go-templates render result.

**Comment by ilya-lesikov** [comment]
In werf v2 there were major changes. Now `werf render` does all the same validations that `werf converge` does. `werf lint` will work the same. Validation became more thorough.

There will be no flag to disable yaml validation, but might be flags to disable other validations. `werf render` now formats the output and will marshal/unmarshal yaml before rendering it, thus the requirement that the result must be valid yaml.
