### ISSUE TITLE
Unnecessary deployment in a case when nothing changes

### ISSUE THREAD

**Issue by alexey-igrychev** [werf/werf#2611]
werf should compare the desired state of deployment with the current one to prevent excess actions such as hooks launching and manifests applying in general.

This logic should be used during deploy procedure and also implemented separately in `werf diff` command.

**Comment by ilya-lesikov** [comment]
Implemented in werf v2. If cluster resources are as expected and manifests in Helm chart not changed then there will be no release. If cluster resources are as expected but only manifests changed, then the new release Secret will be created and the deployment will stop. 

Also there is a `werf plan` command which follows the same logic, showing whether a new release will be created at all or not.
