### ISSUE TITLE
remote docker daemon support (Client sent an HTTP request to an HTTPS server.)

### ISSUE THREAD

**Issue by lingwooc** [werf/werf#2668]
werf doesn't seem to be able to build with a remote docker daemon, that or I've hit a bug with it.

I am using docker-machine to setup the environment variables. Building anything using docker build works quite nicely. 

I've installed werf 1.1 with mutliwerf both locally and remotely and started the symfony demo example.

Run directly on the remote machine `werf build --stages-storage :local` works fine.
Run locally with the env vars for docker set with docker-machine it outputs:
```
werf build --stages-storage :local
Version: v1.0.13
Running time 0.16 seconds
Error: Error response from daemon: Client sent an HTTP request to an HTTPS server.
```
Extra logging (debug) doesn't expand on what it was attempting to do. I appreciate werf uses its own build process so if it genuinely doesn't support a remote docker daemon it should perhaps fail a bit more helpfully. I also checked the docs but perhaps missed a comment.

extra info:
docker machine sets these vars
```
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://xxx.xxx.xxx.xxx:2376"
export DOCKER_CERT_PATH="/xxx/xxx/xxx"
export DOCKER_MACHINE_NAME="xxx"
```

**Comment by lingwooc** [comment]
The response here (#1462) suggests this can't work even if the error above is related to something else

**Comment by distorhead** [comment]
Fixed by the https://github.com/werf/werf/pull/3043
