### ISSUE TITLE
Helm lint and lint-matrix

### ISSUE THREAD

**Issue by alexey-igrychev** [werf/werf#2710]
- values-matrix.yaml testing;
- separate `werf helm lint` and `werf helm lint-matrix` commands;
- automatically call `werf helm lint` during `werf deploy` command.

**Comment by ilya-lesikov** [comment]
lint-matrix feature is too limited. Proper testing support required. Alternatively, this can be solved by providing alternative to Helm templates (TypeScript, ...), where you can write regular tests.

> automatically call werf helm lint during werf deploy command.

We do this now, although validation can be improved.
