### ISSUE TITLE
Support chart repository for publication and deployment

### ISSUE THREAD

**Issue by alexey-igrychev** [werf/werf#2712]
* Saving the state of an application (commit, environment, images) allows sharing it with other users, including end-users.
* Result chart should be fully compatible with Helm.
* Cleanup deny list should take into account images that are used in charts.

**Comment by distorhead** [comment]
Related issue https://github.com/werf/werf/issues/2694

**Comment by distorhead** [comment]
Implemented following commands in the v1.2:

 - `werf bundle publish`;
 - `werf bundle export` (publish bundle into dir);
 - `werf bundle download` (download published bundle into dir);
 - `werf bundle apply` (deploy published bundle into k8s).
