### ISSUE TITLE
import artifact causing rsync @ERROR: invalid uid root

### ISSUE THREAD

**Issue by gkappel** [werf/werf#2762]
seems the issue could be the following generated file
/tmp/werf-project-data-349364264/1q3q6rdprb/import-server/gotemplate/rsyncd.conf

rsync does not seem to like the following, maybe recent versions of rsync are stricter?
   uid = root
   gid = root

I confirmed that if I alter /tmp/werf-project-data-349364264/1q3q6rdprb/import-server/gotemplate/rsyncd.conf to have
   uid = 0
   gid = 0
And manually run docker "rsync server command" below and then a test rsync copy it runs without error

I was unable to find any way to override or control this as it appears to all be generated by werf

$ werf version
v1.1.22+fix29

# werf.yaml excerpt
...
import:
- artifact: gotemplate
  add: /gomplate
  to: /bin/gomplate
  owner: 0
  group: 0
  after: install
...

# log
...
530.285023ms │ │ Stage ecommerce/importsAfterInstall content signature: e98a409e40e9c3841ee0d510e6fb74422db58f514d3ec28be43f40c9
530.316423ms │ │ -- StagesManager.FetchStage ecommerce/install
532.187948ms │ │ -- BuildPhase.prepareStage ⛵ image ecommerce ecommerce/importsAfterInstall
532.220849ms │ │ ┌ Firing up import rsync server for image gotemplate
532.401951ms │ │ │ RunRsyncServer for docker image                                                                                         ↵
532.413851ms │ │ │ "werf-stages-storage/zyus:01b840ed1066caacc91f3666729349bf81bddfc89d575c4542ed6909-1602187650025"
533.87427ms  │ │ │ Run rsync server command: "docker run --detach --rm --user=0:0 --workdir=/                                              ↵
533.886971ms │ │ │ --name=import-server-bf7bc6e8-77c3-49c0-9cb3-3cdf620a2a27 --volumes-from=stapel_0.6.1                                   ↵
533.901471ms │ │ │ --volume=/tmp/werf-project-data-349364264/1q3q6rdprb/import-server/gotemplate/rsyncd.conf:/.werf/rsyncd.conf            ↵
533.923471ms │ │ │ --volume=/tmp/werf-project-data-349364264/1q3q6rdprb/import-server/gotemplate/rsyncd.secrets:/.werf/rsyncd.secrets      ↵
533.948171ms │ │ │ --expose=873 --entrypoint=/.werf/stapel/embedded/bin/rsync                                                              ↵
533.974772ms │ │ │ werf-stages-storage/zyus:01b840ed1066caacc91f3666729349bf81bddfc89d575c4542ed6909-1602187650025 --daemon --no-detach    ↵
534.010372ms │ │ │ --config=/.werf/rsyncd.conf"
1.794320464s │ │ │ Inspect container import-server-bf7bc6e8-77c3-49c0-9cb3-3cdf620a2a27
1.794445765s 
1.794447265s time="2020-10-08T21:45:37Z" level=error msg="error waiting for container: context canceled"
1.795144275s │ │ └ Firing up import rsync server for image gotemplate (1.26 seconds)
1.79557568s  │ │ 
1.79557748s  │ │ Rsync server copy commands for import: artifact="gotemplate" image="" add=/gomplate to=/bin/gomplate includePaths=[]      ↵
1.795601981s │ │ excludePaths=[]: "statOutput=$(RSYNC_PASSWORD='eac6cdda3de13218d95dcfd25d4fc422' /.werf/stapel/embedded/bin/rsync -L      ↵
1.795623181s │ │ rsync://werf-80cf37fe@172.17.0.2:873/import//gomplate) && [ $? -eq 0 ] && unset IMPORT_PATH_TRAILING_SLASH_OPTIONAL &&    ↵
1.795652581s │ │ fileTypeField=$(echo $statOutput | /.werf/stapel/embedded/bin/head -c1) && [ $? -eq 0 ] && if [ $fileTypeField = d ] ;    ↵
1.795699982s │ │ then IMPORT_PATH_TRAILING_SLASH_OPTIONAL=/ ; fi && /.werf/stapel/embedded/bin/mkdir -p /bin &&                            ↵
1.795739282s │ │ RSYNC_PASSWORD='eac6cdda3de13218d95dcfd25d4fc422' /.werf/stapel/embedded/bin/rsync --archive --links --inplace            ↵
1.795788483s │ │ --chown=0:0 rsync://werf-80cf37fe@172.17.0.2:873/import//gomplate$IMPORT_PATH_TRAILING_SLASH_OPTIONAL /bin/gomplate"
1.796523593s │ │ ┌ Building stage ecommerce/importsAfterInstall
2.190655316s │ │ │ ecommerce/importsAfterInstall  @ERROR: invalid uid root
2.190664816s │ │ │ ecommerce/importsAfterInstall  rsync error: error starting client-server protocol (code 5) at main.c(1648)              ↵
2.190695016s │ │ │ ecommerce/importsAfterInstall  [Receiver=3.1.2]
2.261041552s time="2020-10-08T21:45:38Z" level=debug msg="[hijack] End of stdout"
2.468039104s │ │ ├ Info
2.468066305s │ │ └ Building stage ecommerce/importsAfterInstall (0.67 seconds) FAILED
2.468099605s │ └ Phase build -- OnImageStage() (1.98 seconds) FAILED
2.468138406s └ ⛵ image ecommerce (1.98 seconds) FAILED
...

**Comment by distorhead** [comment]
Seems like uid=root, gid=root setting depends on `root:x:0:0:...` line in the /etc/passwd of artifact, while uid=0, gid=0 is more portable setting.

Reproduced this error by removing /etc/passwd in the artifact.

https://github.com/werf/werf/pull/2763

Fix release will come in 15 min.

**Comment by distorhead** [comment]
Done, thanks for report!
