### ISSUE TITLE
werf-export command

### ISSUE THREAD

**Issue by distorhead** [werf/werf#2868]
Implement werf-export command to export images defined in the `werf.yaml` and built by the werf into arbitrary docker-registry.

Werf-export command is like docker-tag command. This command will transfer image that is internally managed by the werf into some registry and this exported image is no longed managed by the werf. This means that `werf_image` helm template cannot be used to automatically generate an exported docker-image name for example.

**Comment by distorhead** [comment]
Addition: implement `--squash|--full-squash` options to squash layers of exported image into the single layer.

**Comment by alexey-igrychev** [comment]
https://github.com/werf/werf/pull/3677
