### ISSUE TITLE
Implement --tag option for werf-converge and werf-render

### ISSUE THREAD

**Issue by distorhead** [werf/werf#2869]
- `--tag` option should force tagging by the specified tag when publishing a newly built image.
 - this tag will also be used by the `werf_image` template which generates a full docker image name for helm templates.
 - werf-converge and werf-render commands should support `--tag` flag.
 - `--tag` flag specifies a template, by which each image defined in the werf.yaml will be tagged.

For example, suppose we have the following werf.yaml:

```
image: backend
dockerfile: Dockerfile.backend
---
image: frontend
dockerfile: Dockerfile.frontend
```

`--tag {{ $image_name }}-latest --repo myregistrydomain.com/myproject` options should generate the following docker images names for `backend` and `frontend` werf short names:

```
myregistrydomain.com/myproject:backend-latest
myregistrydomain.com/myproject:frontend-latest
```

**Comment by alexey-igrychev** [comment]
https://github.com/werf/werf/releases/tag/v1.2.28
