### ISSUE TITLE
Build fails after switching to converge from build-and-push

### ISSUE THREAD

**Issue by konstantin-axenov** [werf/werf#3002]
Needed to make changes to werf.yaml otherwise always received an error
```
Error: dockerfile 'dockerfiles/csv-generator/dockerfiles/csv-generator/Dockerfile' was not found in local git repository
```

![image](https://user-images.githubusercontent.com/14013249/101658103-bc41eb80-3a55-11eb-99d4-7df4d553b2ae.png)

Is it correct behavior?

**Comment by distorhead** [comment]
Hello!

It is a breaking change which has been introduced in the alpha v1.2.1 (beta v1.2.0 will work with your old config). From now and on we will specify `dockerfile`-s relatively to the specified `context`.

Sorry for the bad user experience, but we need to change this behaviour in v1.2.

**Comment by konstantin-axenov** [comment]
Is there any doc that can be linked to this issue in case someone has the same problem?

**Comment by distorhead** [comment]
Newer v1.2.1: https://werf.io/v1.2-alpha/documentation/reference/werf_yaml.html

![image](https://user-images.githubusercontent.com/1161992/101660558-5dca3c80-3a58-11eb-9904-31b47cf5fdbd.png)

Older v1.2.0: https://werf.io/documentation/reference/werf_yaml.html

![image](https://user-images.githubusercontent.com/1161992/101660526-55720180-3a58-11eb-9286-37f562960dc1.png)
