### ISSUE TITLE
Converge ignores env WERF_KUBECONFIG_BASE64

### ISSUE THREAD

**Issue by konstantin-axenov** [werf/werf#3003]
Werf deploy works fine. But when I switch to converge it seems that my kubeconfig is ignored.
```
Error: Kubernetes cluster unreachable: Get "http://localhost:8080/version?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
```

**Comment by distorhead** [comment]
Currently v1.2 does not support KUBECONFIG_BASE64. But we will add this support ASAP if you need it.

**Comment by distorhead** [comment]
https://github.com/werf/werf/blob/master/pkg/deploy/helm/init.go#L42

**Comment by konstantin-axenov** [comment]
Thanks. It can wait a little bit.

**Comment by distorhead** [comment]
@konstantin-axenov It is better to keep this issue opened ;)
