### ISSUE TITLE
[v1.2, dockerfile] BuildKit is not supported

### ISSUE THREAD

**Issue by alexey-igrychev** [werf/werf#3028]
Do not use BuildKit until:
* The following issues with [BuildKit build](https://github.com/docker/cli/tree/40ec81a79afb993d3f77042194ad81a2a8b466a7/cli/command/image/build_buildkit.go) are not resolved:
  * BuildKit implementation uses standard streams instead of [docker client instance ones](https://github.com/docker/cli/tree/40ec81a79afb993d3f77042194ad81a2a8b466a7/cli/command/cli.go#L51-L53).
  * Reading context/dockerfile from the docker client stdin does not work (fix [here](https://github.com/docker/cli/pull/2885)).
  * The command output is written to the standard output and error streams, and we cannot process it.
* The use of the docker build command is not rewritten to the docker API.

**Comment by distorhead** [comment]
https://github.com/werf/werf/pull/3367
