### ISSUE TITLE
Added .Values.global.werf.name service value with werf cli util project name

### ISSUE THREAD

**Issue by alchazov** [werf/werf#3230]
use for name in helm subcharts

**Comment by distorhead** [comment]
Have you tried helm 3 library charts? https://helm.sh/docs/topics/library_charts/

It is specially designed charts to be included into some chart, so it has an access for main chart `.Values` without `global`. Regular charts should be independent of such values, there should be ability to deploy a regular chart as a standalone application/component or to include it as subchart into some other chart. Library chart cannot be used as a standalone, it should be always included into some main chart, so it has an access for the main chart `.Values`.

Also there is a `.Release.Name` special value which should be accessible in the main chart and subcharts.

BTW added `.Values.global.werf.name` which contains project name from werf.yaml, the same as `.Values.werf.name`: https://github.com/werf/werf/pull/3231.
