### ISSUE TITLE
Error: UPGRADE FAILED: "release" has no deployed releases

### ISSUE THREAD

**Issue by distorhead** [werf/werf#3275]
Sometimes this error occurs in the v1.2.

1. Deploy release with the werf-converge.
2. Then delete release with the werf-helm-delete.
3. Then deploy release with the werf-converge.

https://github.com/helm/helm/blob/master/pkg/action/upgrade.go#L158

Maybe this is race condition, when delete has not been fully done yet?

**Comment by ilya-lesikov** [comment]
Should not be happening in werf v2, because even if no release Secret found during `werf dismiss`, then it will just exit with exit code 0.
