### ISSUE TITLE
Support tracking for different hook resources kinds, other that Jobs

### ISSUE THREAD

**Issue by distorhead** [werf/werf#3340]
Werf for not does not support tracking any hook kinds other than Job, printing the warning like:

```
Will not track helm hook statefulset/X: StatefulSet kind not supported for tracking
```

Werf should support some basic fallback tracking for any kind of resource of helm hook.

**Comment by distorhead** [comment]
Related issue https://github.com/werf/kubedog/issues/182

**Comment by ilya-lesikov** [comment]
Done in https://github.com/werf/kubedog/pull/255
