### ISSUE TITLE
[synchronization-server] Stages storage cache delete all stages operation internal error

### ISSUE THREAD

**Issue by distorhead** [werf/werf#3366]
DeleteAllStages synchronization server stages storage cache operation caused sudden internal error: 

```
Error: unable to remove /root/.werf/synchronization_server/stages_storage_cache/91afe3cd-008d-418a-b563-0dc40fa66b9c/deckhouse-web: unlinkat /root/.werf/synchronization_server/stages_storage_cache/91afe3cd-008d-418a-b563-0dc40fa66b9c/deckhouse-web: directory not empty
```

1. This error occurred in the os.RemoveAll system golang call. Why?
2. Maybe we should remove files in the files-stages-storage-cache differently.

**Comment by alexey-igrychev** [comment]
we do not use sync server for cache anymore.
