### ISSUE TITLE
Is Dockerfile.dockerignore supported?

### ISSUE THREAD

**Issue by bard** [werf/werf#3460]
I've searched the docs and glanced at the code and found nothing, so I guess the answer is no, however since this is a likely blocker for me I thought I'd ask explicitly.

Background: https://github.com/moby/buildkit/pull/901, https://github.com/GoogleContainerTools/kaniko/issues/776.

**Comment by distorhead** [comment]
Hi! Werf supports .dockerignore.

https://github.com/werf/werf/blob/master/pkg/giterminism_manager/file_reader/dockerfile.go#L58

**Comment by bard** [comment]
Thanks @distorhead. Too bad. Any plans of supporting `Dockerfile.dockerignore` too in the future?

**Comment by alexey-igrychev** [comment]
@bard 
The functionality will be available in the next release (https://github.com/werf/werf/pull/3516).

**Comment by alexey-igrychev** [comment]
Available since https://github.com/werf/werf/releases/tag/v1.2.10%2Bfix25.
