### ISSUE TITLE
werf-helm-template command --debug does not affect output

### ISSUE THREAD

**Issue by distorhead** [werf/werf#3473]
`--debug` flag for the werf-helm-template is broken and does not affect helm output.

Workaround: use `werf render --debug`.

**Comment by imcitius** [comment]
It would be great to check if this works as expected during converge.

**Comment by ilya-lesikov** [comment]
Nelm project will take the place of `werf helm` in time. In Nelm engine there is no problem with `--debug`. Closing this for now.
