### ISSUE TITLE
werf.yaml git always use default remote branch instead of target

### ISSUE THREAD

**Issue by AlexPerov** [werf/werf#3493]
werf.yaml
git:
...
- url: git@github.com:account/repo.git
  branch: test
  herebyIAdmitThatBranchMightBreakReproducibility: true

at the result i have branch master in pod after deploy

even in logs presents correct git branch and url, but this behavior ignores target branch

**Comment by alexey-igrychev** [comment]
I apologize for the delayed response, especially after two years. 
I've attempted to replicate your issue across versions 1.1, 1.2, and 2, and everything works fine. It's likely that your problem is unrelated to this.
