### ISSUE TITLE
ARM support?

### ISSUE THREAD

**Issue by Faust13** [werf/werf#3499]
Hi there! We are use WERF in production and wanna use the same way for local development with minikube.
It will be great if werf supports the ARM architecture, especially after the Apple M1 release.

**Comment by distorhead** [comment]
Hi!

We have plans to publish builds for arm64: https://github.com/werf/werf/issues/3175 and https://github.com/werf/werf/issues/3176.

Official builds will be available in month or two.

For now it is possible to build werf on your machine by installing golang and running `./go-build.sh` in the root of the werf repo worktree.

**Comment by manycoding** [comment]
Any updates? Why building werf locally enables m1 support?

**Comment by maximseshuk** [comment]
Any updates?

**Comment by JenspederM** [comment]
Any updates?

**Comment by distorhead** [comment]
Hi! Official arm64 werf builds are available for v1.2. See Installation links in the github release (for example https://github.com/werf/werf/releases/tag/v1.2.80) or just use trdl to install and activate werf (https://werf.io/installation.html?version=1.2&channel=stable&os=macos&arch=amd64&method=manually#install-werf).

**Comment by alexbechmann** [comment]
hi @distorhead 

I still have issues building ARM64 images with this version

```bash
werf build

Version: v1.2.72
werf currently does not support building of images for any other platform      ↵
besides linux/amd64.
Please set --platform option (or WERF_PLATFORM, or DOCKER_DEFAULT_PLATFORM     ↵
environment variable) to linux/amd64 to enable platform emulation when         ↵
building images with werf.
```

**Comment by allnightlong** [comment]
hi @distorhead

I've run into this issue yesterday:

```
werf converge --repo myrepo --platform linux/arm64 --dev --verbose
Version: v1.2.162
werf currently does not support building of images for any other platform besides linux/amd64.
Please set --platform option (or WERF_PLATFORM, or DOCKER_DEFAULT_PLATFORM environment variable) to linux/amd64 to enable platform emulation when building images with werf.

Running time 0.04 seconds
Error: unable to init process docker for docker-server container backend: unable to init docker for buildah container backend: unsupported platform
```

**Comment by ch1seL** [comment]
Hi @distorhead 
```

System Version: macOS 12.6 (21G115)
Kernel Version: Darwin 21.6.0
Chip: Apple M1 Pro
```


```
werf build  
Version: v1.2.175+fix3
werf currently does not support building of images for any other platform besides linux/amd64.
Please set --platform option (or WERF_PLATFORM, or DOCKER_DEFAULT_PLATFORM environment variable) to linux/amd64 to enable platform emulation when building images with werf.
```

**Comment by ch1seL** [comment]
Hi @distorhead, thank you for answer!

> For local macos development just use emulation for now

This is the stumbling block. A lot of thinks doesn't work properly for example I can't just run default asp net core application without crutches because of https://github.com/dotnet/aspnetcore/issues/38876, mongodb doesn't support linux/amd64 emulation and etc, etc..
