### ISSUE TITLE
Releases location

### ISSUE THREAD

**Issue by borgius** [werf/werf#3512]
Good morning!

Can you guys duplicate binaries to GitHub, because corporate GW does not allow to download from Yandex cloud?

Thank you!

**Comment by mbhavya** [comment]
![image](https://user-images.githubusercontent.com/1161767/116430391-6b942900-a864-11eb-8441-bf5010a5c786.png)

**Comment by alexey-igrychev** [comment]
We provide geographically distributed storage for our releases, so you don't need to worry about the availability of release artifacts.

**Comment by ilya-lesikov** [comment]
And now binaries can be found here:
https://tuf.werf.io/targets/releases/2.4.0/linux-amd64/bin/werf
