### ISSUE TITLE
werf cleanup: unsupported action "delete"

### ISSUE THREAD

**Issue by VAveryanov8** [werf/werf#3598]
Hi! I'm using werf 1.1 stable and during werf cleanup step in gitlab-ci I see following warnings: 
```bash
$ type werf && source $(werf ci-env gitlab --as-file)
werf is a function
werf () 
{ 
    /home/gitlab-runner/.multiwerf/v1.1.23+fix47/werf-linux-amd64-v1.1.23+fix47 "$@"
}
...
│ │ │ ┌ Deleting tags
│ │ │ │ WARNING: Image gcr.io/*****/repo:e8asd70f6bc73b22671asdasd33bea128bcasdc80b ↵
│ │ │ │ 2a9895c4c01f70a deletion failed: GET https://gcr.io/v2/token?scope=repository%3A****%2F******%3Apush&scope=repository%3A*******%2F******%3Apull&scope=rep ↵
│ │ │ │ ository%3A*******%2F*****%3Adelete&service=gcr.io: UNKNOWN: Unsupported       ↵
│ │ │ │ action: "delete".
```
Should I be worried about those warnings? 
P.S.
Docker repository is a private GCR repo. 

Thanks in advance!

**Comment by alexey-igrychev** [comment]
I apologize for not responding to the issue earlier. Is the issue still relevant?

**Comment by VAveryanov8** [comment]
@alexey-igrychev No worries! Yes, I can still see these warnings in a logs of a cleanup job

**Comment by alexey-igrychev** [comment]
Try to run the cleanup explicitly specifying the container registry type:
- `--images-repo-implementation=gcr` (or `WERF_IMAGES_REPO_IMPLEMENTATION=gcr`) for v1.1;
- `--repo-container-registry=gcr` (or `WERF_REPO_CONTAINER_REGISTRY=gcr`) for v1.2.

**Comment by VAveryanov8** [comment]
Looks like your suggestion helped! Thanks! I'm closing this issue 👍
