### ISSUE TITLE
Local Werf build without using existing cache

### ISSUE THREAD

**Issue by saurabhkdm** [werf/werf#3618]
Werf used cache on the local machine to build. External packages changes do not get detected in the werf. Is there any way to build images even if the cache exists on the local machine?

**Comment by icecom-dg** [comment]
If you are referring to changes in the base images, you have three options:
1. Use an unchangeable tag  for the base image in the `from` directive and bump it when you want to use a newer version.
2. Specify an arbitrary string in the `fromCacheVersion` directive and change it when you want to build from a newer version.
3. Set `fromLatest: true` to always use the latest base image. **Using this directive is NOT recommended** as it introduces an external dependency and, therefore, violates reproducibility guarantees.

You can read more about these directives [in the documentation](https://werf.io/documentation/v1.2/advanced/building_images_with_stapel/base_image.html). To learn more about some of the ideas behind werf, read [this article about _giterminism_](https://werf.io/documentation/v1.2/advanced/giterminism.html).

**Comment by saurabhkdm** [comment]
Closing this issue...
