### ISSUE TITLE
Error: Kubernetes cluster unreachable: no such file or directory

### ISSUE THREAD

**Issue by Noksa** [werf/werf#3670]
Using werf v1.2.13+fix6.

I'm trying to run the following command:
`werf helm test RELEASE_NAME`

But get an error:
`Error: Kubernetes cluster unreachable: stat /home/alexandr/.kube/config:/home/alexandr/.kube/minikube_config: no such file or directory`

I have two config files and use KUBECONFIG variable:
`export KUBECONFIG="/home/alexandr/.kube/config:/home/alexandr/.kube/minikube_config"` (https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/#the-kubeconfig-environment-variable)

I tried `werf helm` commands on 1.1 werf as well and got the same error:
`Error: stat /home/alexandr/.kube/config:/home/alexandr/.kube/minikube_config: no such file or directory`

Is it possible to use werf with multiple kube config files from KUBECONFIG variable?

**Comment by alexey-igrychev** [comment]
werf/kubedog does not handle multiple paths correctly, and we will definitely fix this in the coming weeks.

**Comment by alexey-igrychev** [comment]
rel https://github.com/werf/werf/issues/3670 https://github.com/werf/werf/pull/3696

**Comment by ilya-lesikov** [comment]
Must be fixed here https://github.com/werf/werf/pull/3696
