### ISSUE TITLE
Userspace build tools without docker

### ISSUE THREAD

**Issue by ruckc** [werf/werf#3687]
As a user, I prefer podman/buildah for doing rootless local builds.  It would be nice to support alternative container build tools that support rootless builds.

**Comment by tumauwt** [comment]
I as well. This is similar to issue #1618

**Comment by alexey-igrychev** [comment]
This week we begin to investigate buildah. Follow updates [here](https://github.com/werf/werf/discussions/3014#discussioncomment-1277397).

**Comment by distorhead** [comment]
Closing this issue if favor of https://github.com/werf/werf/issues/1618
