### ISSUE TITLE
JetBrains Space Container registry support

### ISSUE THREAD

**Issue by develar** [werf/werf#3688]
JetBrains Space Container registry — https://www.jetbrains.com/help/space/publish-images.html

It seems Werf cannot correctly parse URLs like

```
mycompany.registry.jetbrains.space/p/projectkey/mydocker/myimage
```

The issue — `/p/`.  So, I get auth error.

> unexpected status code 403 Forbidden: Access to repository 'p' denied

**Comment by dtretyakov** [comment]
It's not clear to me why `werf` uses hard-coded list of integrations: https://github.com/werf/werf/blob/main/pkg/docker_registry/docker_registry.go

All popular docker/OCI tools are using client API written in goland which could use standard docker credentials. Typically all of such integrations are provided by service developers as an [additional docker credentials helper](https://github.com/docker/docker-credential-helpers/), e.g. [Azure](https://github.com/Azure/acr-docker-credential-helper), [JetBrains Space](https://github.com/JetBrains/docker-credential-space).

Please consider following the standard of docker credentials helper protocl to make `werf` work in different environments.

**Comment by alexey-igrychev** [comment]
@dtretyakov, In most cases, specifying the container registry is not required, and everything will work without any issues (the user should only execute docker login and specify repo).

The container registry type and additional data are required when using cleanup commands since most container registries use a native API. More details in [the documentation](https://werf.io/documentation/v1.2/advanced/supported_container_registries.html).

> Please consider following the standard of docker credentials helper protocl to make werf work in different environments.

Many parameters can indeed be obtained from docker config, and we'll fix it.

Thanks for the feedback.

**Comment by alexey-igrychev** [comment]
@develar I tried and did not encounter any problems with it.

```
$ echo $SPACE_PAT | docker login werf.registry.jetbrains.space -u alexey.igrychev --password-stdin
$ werf build --repo=werf.registry.jetbrains.space/p/werf/containers/myimage
Version: v1.2.15+fix2
Using werf config render file: /tmp/werf-config-render-2241789960

┌ Getting client id for the http synchronization server
│ Using clientID "6cfd970c-3f80-41e3-b2e2-584504b8823b" for http synchronization server at address                                                           ↵
│ https://synchronization.werf.io/6cfd970c-3f80-41e3-b2e2-584504b8823b
└ Getting client id for the http synchronization server (0.90 seconds)

┌ Concurrent builds plan (no more than 5 images at the same time)
│ Set #0:
│ - ⛵ image test
│ - ⛵ image test2
└ Concurrent builds plan (no more than 5 images at the same time)

┌ ⛵ image test
│ ┌ Copy suitable stage from secondary :local
│ │ Use cache image for test/from
│ │      name: werf.registry.jetbrains.space/p/werf/containers/myimage:85279ff0e1713f78e68b4356b2fa6a889e85b260e1ba7cf8d3ea09d3-1629998411282
│ │        id: e481fe8b92f2
│ │   created: 2021-08-26 19:20:11 +0200 CEST
│ │      size: 2.7 MiB
│ └ Copy suitable stage from secondary :local (7.32 seconds)
│
│ ┌ Copy suitable stage from secondary :local
│ │ Use cache image for test/gitArchive
│ │      name: werf.registry.jetbrains.space/p/werf/containers/myimage:4d11c3ab793f678696ac0d3b8bd1c92fe6dafc01d285e004bf3781ec-1629998412177
│ │        id: 608e7fca905d
│ │   created: 2021-08-26 19:20:12 +0200 CEST
│ │      size: 2.7 MiB (+364 B)
│ └ Copy suitable stage from secondary :local (6.69 seconds)
```

![jetbrains](https://user-images.githubusercontent.com/17360817/132222797-a26a75f3-d2e0-426d-bb39-c568bb8dcd57.png)

**Comment by develar** [comment]
Thanks for the confirmation, that it should work.
Same UX issue like https://github.com/werf/werf/discussions/3630

I set repo to URL of my container registry `registry.jetbrains.team/p/ij-developer-dashboard/containers`, but Werf expects that it will include also project name (`registry.jetbrains.team/p/ij-developer-dashboard/containers/project-name`).
