### ISSUE TITLE
Problem while parsing werf-synchronization param with @

### ISSUE THREAD

**Issue by duckhawk** [werf/werf#3881]
While using context in --synchronization, parser cannot parse context if it contains @.
For example, if there is something like kubernetes://myshinenamespace:kubernetes-admin@kubernetes, parser trying to get base64 config_data from "kubernetes", and fails.

**Comment by ilya-lesikov** [comment]
The recommended way to connect to the self-hosted sync server is through https:
```shell
--synchronization https://synchronization.domain.org
```
Expose your sync server via Ingress and connect it this way.

`--synchronization kubernetes://...` is deprecated now.
