### ISSUE TITLE
Linting with golangci-lint

### ISSUE THREAD

**Issue by alexey-igrychev** [werf/werf#3898]
- Default linters

    - [x] deadcode
    - [ ] errcheck
    - [ ] govet
    - [x] ineffassign
    - [x] structcheck
    - [x] typecheck
    - [x] varcheck
    - [ ] unused

- Extra linters

    - [x] asciicheck
    - [x] bidichk
    - [x] bodyclose
    - [ ] contextcheck
    - [ ] cyclop
    - [ ] dupl
    - [x] errname
    - [ ] errorlint
    - [x] exportloopref
    - [ ] forcetypeassert
    - [x] gci
    - [ ] gochecknoinits
    - [ ] godot
    - [ ] gomnd
    - [x] gocritic
    - [x] gofumpt
    - [ ] gosec
    - [ ] ireturn
    - [ ] nilerr
    - [ ] nilnil
    - [ ] noctx
    - [x] misspell 
    - [ ] revive
    - [ ] unparam
    - [ ] varnamelen

**Comment by alexey-igrychev** [comment]
rel https://github.com/werf/werf/issues/4103

**Comment by ilya-lesikov** [comment]
We are satisfied with whatever linters we have now.
