### ISSUE TITLE
Minor Mistake In Install Documents

### ISSUE THREAD

**Issue by Namphibian** [werf/werf#4062]
More a FYI than a problem.

In the [Springboot getting started](https://werf.io/guides/java_springboot/100_basic/20_cluster.html) guide when you modify the hosts files the domain names are different to the one you will use in the curl command.

We add werf-guide-app.test to the host file with the minikube ip see below:

`echo "$(minikube ip) werf-guide-app.test" | sudo tee -a /etc/hosts`

Then we do a curl to another domain name see below:
`curl http://werf-guide-app/ping`
`curl: (6) Could not resolve host: werf-guide-app`

If you change the curl command to:
`curl http://werf-guide-app.test/ping`

You will get the 404.

**Comment by ilya-lesikov** [comment]
Hello, thanks, we'll fix this soon.
