### ISSUE TITLE
Stages created in dev-mode are not reused after commit

### ISSUE THREAD

**Issue by alexey-igrychev** [werf/werf#4113]

**Comment by ilya-lesikov** [comment]
**Local development got faster: in `--dev` mode already built stages are reused more often (v1.2.65)**

Additionally:
1. Multiple service branches `werf-dev-XXXXX` were created when working in a dev-mode, now we create only a single branch — `_werf_dev`.
2. Option `--dev-branch-prefix` replaced with `--dev-branch`.
3. Old service branches can be deleted now: `git branch --list 'werf-dev-*' | cut -c3- | xargs git branch -D`
