### ISSUE TITLE
Add support for homebrew installation

### ISSUE THREAD

**Issue by remyleone** [werf/werf#4368]
I've found this: https://werf.io/installation.html?version=1.2&channel=stable&os=macos&arch=amd64&method=installer

It works but I would like to have this package managed by my package manager who is homebrew on macOS.

**Comment by Sebor** [comment]
@remyleone today I have installed werf via brew:
```bash
brew install werf
```

**Comment by mindw** [comment]
On WSL2 (Linux) installation fails - 
```
$ brew install -v werf
werf: macOS is required for this software.
Error: werf: An unsatisfied requirement failed this build.
```

**Comment by Sebor** [comment]
Oh, you didn't mention that you use brew on linux :)

**Comment by ilya-lesikov** [comment]
We understand why some might prefer using their favorite package manager, but we have no plans to support other installation options as of now.

Will reopen if something changes.
