### ISSUE TITLE
Cannot converge with Kubernetes executor.

### ISSUE THREAD

**Issue by abrekhov** [werf/werf#4409]
I've launched gitlab-runner with serviceAccount which is cluster admin. I used experimental docs. And I got such error:

```Error: unable to create lock manager: get ConfigMap werf-synchronization error: configmaps "werf-synchronization" is forbidden: User "system:serviceaccount:ingresses-54-staging:ingresses-54-staging-service-account" cannot get resource "configmaps" in API group "" in the namespace "platform-staging"```

I do not understand why here system:serviceaccount:ingresses-54-staging. Is it depends on gitlab environment?

Thanks!

**Comment by abrekhov** [comment]
UPD: if I do not using environment in gitlab-ci.yml - everything is ok.

**Comment by ilya-lesikov** [comment]
Needs further investigation: https://gitlab.com/gitlab-org/gitlab-runner/-/issues/26090

For now you can try to mess around with `KUBERNETES_SERVICE_ACCOUNT_OVERWRITE` environment variable and `service_account_overwrite_allowed` GitLab Runner option: https://docs.gitlab.com/runner/executors/kubernetes.html#overwriting-kubernetes-default-service-account
