### ISSUE TITLE
Multi-platform builds

### ISSUE THREAD

**Issue by alexey-igrychev** [werf/werf#4482]

**Comment by alexey-igrychev** [comment]
rel #3499 #2389

**Comment by alexbechmann** [comment]
@alexey-igrychev Any update on this topic? I am in need of this feature to build ARM64 docker images with this tool :)

**Comment by alexey-igrychev** [comment]
Sorry for the delay. Currently, you can choose any target platform and build images with the Buildah backend (Dockerfile and Stapel supported). 

Read more about userspace builds [here](https://werf.io/documentation/v1.2/advanced/buildah_mode.html) and about using in CI/CD [here](https://werf.io/documentation/v1.2/advanced/ci_cd/run_in_container/use_docker_container.html) (in Docker container) and [here](https://werf.io/documentation/v1.2/advanced/ci_cd/run_in_container/use_kubernetes.html) (in Kubernetes).

**Comment by distorhead** [comment]
@alexbechmann Hi there!

Currently werf supports building images for arbitrary platforms as well as multiplatform images. Details are here: https://github.com/werf/werf/discussions/5642

**Comment by alexbechmann** [comment]
Hey @distorhead 

Ah very nice! Thanks for the update, I look forward to trying this!
