### ISSUE TITLE
importBeforeInstall not invalidating cache as expected

### ISSUE THREAD

**Issue by Zsmith32** [werf/werf#4497]
Hello,

We're using Werf v1.2.54.

We have two images one base and a second that we are importing files from. We're using npm so we're importing node_modules from the base image into the second. Sometimes we're seeing that the "second/importBeforeInstall" stage is using an outdated cached install stage.

In our build we expect the package.json and package-lock.json to trigger a new install stage on changes. We do successfully see that this install stage correctly rebuilds on changes. The problem is second will not always use this new stage. 

Is there some option we're missing in the "second" image below to trigger a cache invalidation? Or maybe this is fixed in a newer version of werf?

Our werf files look like this (some details excluded for company policies):

---
image: base
git:
  - add: /
    to: /some/path
    includePaths:
      - "package.json"
      - "package-lock.json"
    stageDependencies:
      install:
        - "package.json"
        - "package-lock.json"
shell:
  install:
    - cd /some/path
    - npm ci --ignore-scripts --no-audit --prefer-offline --no-fund
---
image: second

git:
  - add: /some/other/path
    to: /another/path 

import:
  - image: base
    add: /some/path
    to: /some/path/
    before: install
    stage: install
    includePaths:
        - node_modules

shell:
  install:
    - ls /some/path/node_modules
---

**Comment by alexey-igrychev** [comment]
Thank you for your feedback!

In version 1.2, we implemented several related fixes that likely resolve this issue. 

Additionally, note the specific behavior of imports with the stapel builder. To minimize potential rebuilds, we calculate a checksum of the imported files, which determines the rebuild. Therefore, even if the source image is rebuilt, the import might not trigger if the file checksum remains unchanged.

We appreciate your patience and support.
