### ISSUE TITLE
Error: phase build on image <image-name>.... stage setup handler failed.... Error: No such container werf.build.7wk55nkcbg

### ISSUE THREAD

**Issue by Zsmith32** [werf/werf#4529]
Hi a recent build of ours for <image-name> ran the entire setup stage, then after the last command in our setup stage we got his error:
Error: phase build on image <image-name> stage setup handler failed: failed to build image for stage setup with digest <hash>: Error: No such container: werf.build.7wk55nkcbg

I'm not sure what to make of this error message or how to prevent it from happening. Any suggestions or information about what this means would be helpful

**Comment by distorhead** [comment]
Hi!

Possible reason of this is that build container was removed by something external during building of setup stage. If you run builds on kubernetes node, then kubelet could cleanup excess docker containers and images.

Internal mechanics of stapel stages builder: run docker container named `werf.build.RANDOM` with user instructions, then commit image from this container, then push it into the container registry.
