### ISSUE TITLE
"werf helm template" does not render {{ .Values.werf.image.image_name }}

### ISSUE THREAD

**Issue by CRASH-Tech** [werf/werf#4532]
Just empty string without error

**Comment by alexey-igrychev** [comment]
You should use `werf render` instead. The `werf helm *` commands do not integrate with building images (and other service values).

**Comment by CRASH-Tech** [comment]
> You should use `werf render` instead. The `werf helm *` commands do not integrate with building images (and other service values).

This breaks compatibility at the helm commands level and creates problems when integrating into third-party CD/pipelines
