### ISSUE TITLE
Difference in version naming between brew (mac) or direct binary download

### ISSUE THREAD

**Issue by rerime** [werf/werf#4562]
Difference in version naming between `brew  install` or direct binary download

```
werf version
1.2.117
```
or
```
werf version
v1.2.117
```

Please make consistent

**Comment by ilya-lesikov** [comment]
Whatever you install via brew is not supported or shipped by us. All the supported ways to install werf are mentioned on our site: https://werf.io/installation.html The recommended way is to install via `trdl` — it is very secure and provides seamless werf updates.

If you really want brew, I think the question should be asked somewhere here: https://github.com/Homebrew/homebrew-core
At first glance it looks like the problem might be that the werf version passed without the "v" prefix here: https://github.com/Homebrew/homebrew-core/blob/a036681a810470f45b10447488e5a9ab70f77f06/Formula/werf.rb#L30
