### ISSUE TITLE
Provide push only custom tags to final repo

### ISSUE THREAD

**Issue by onegreyonewhite** [werf/werf#4636]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Problem

When a werf is used to build public images without the deployment, it would be very convenient for users to see only the final images and human-readable tags.

Now werf push to the final repo a lot of meta-information, which can confuse users.

![image](https://user-images.githubusercontent.com/12040552/179644266-2b7fc55c-002b-411b-8656-2035bf5d0d7b.png)

It would be nice to have argument for `werf build` command, which means that only custom tags respected for push in final repo.

**Comment by alexey-igrychev** [comment]
In this case, it would be more appropriate to use the `werf export` command, which allows you to publish images to arbitrary repositories for later use without werf.

```
werf export --repo ghcr.io/group/project --tag ghcr.io/group/otherproject/%image%:latest
```

**Comment by onegreyonewhite** [comment]
> In this case, it would be more appropriate to use the `werf export` command, which allows you to publish images to arbitrary repositories for later use without werf.
> 
> ```
> werf export --repo ghcr.io/group/project --tag ghcr.io/group/otherproject/%image%:latest
> ```

May be it should be combined with #4637. Thank you for answer, combination of `werf build` and `werf export` covers my usecase.

**Comment by alexey-igrychev** [comment]
This metadata is really not needed, and we should not add it to the final repository.

<img width="961" alt="Screenshot 2022-07-19 at 12 04 03" src="https://user-images.githubusercontent.com/17360817/179735683-42ecd87a-e585-4060-b171-10ea3beb6f56.png">

**Comment by distorhead** [comment]
When using `--final-repo` param, this repo would contain only user images, without metadata, while `--repo` would contain metadata:

![Screenshot from 2022-08-23 10-44-41](https://user-images.githubusercontent.com/1161992/186101381-fd34741f-2042-40a7-a7b2-268bd51059ec.png)

So if you need to hide werf metadata from user, then I recommend using some reserved subrepo for primary repo (`/storage` for example) and regular repo as final repo for user:
* `--final-repo=registry.mydomain.org/project`
* `--repo=registry.mydomain.org/project/storage`

**Comment by distorhead** [comment]
FIxed in https://github.com/werf/werf/pull/4839, repo and final repo after build will look like that:

![Screenshot from 2022-08-24 18-15-21](https://user-images.githubusercontent.com/1161992/186456397-a9d9ccfd-22c9-4845-a605-df524ded177b.png)
