### ISSUE TITLE
Converge error caused by a limited access to the "namespaces" API request

### ISSUE THREAD

**Issue by azahi** [werf/werf#4652]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Version

1.2.133

### How to reproduce

1. Create a Kubernetes cluster in such a way that a user only has access to a single namespace and cannot query all available namespaces.
2. Run `werf converge` with appropriate arguments specifying the aforementioned namespace as a deploy target.
3. Encounter an error.

### Result

```
$ werf converge
Version: v1.2.133
Using project dir: /home/gitlab-runner/builds/Cd16pniE/0/group/project
Using werf config render file: /tmp/werf-config-render-2986957871
Use cache image for app/dockerfile
     name: registry.example.ru/group/project:99c57bd6600534419ca852f7ea7fadc158e692a7fbb5f96f55457a4a-1658407938087
       id: 602770a0b154
  created: 2022-07-21 15:52:17 +0300 MSK
     size: 145.7 MiB
Running time 0.20 seconds
Error: unable to create lock manager: get Namespace project-stage error: namespaces "project-stage" is forbidden: User "oidc:user@example.ru" cannot get resource "namespaces" in API group "" in the namespace "project-stage"
```

### Expected result

Deploy succeeded.

### Additional information

Bug was encountered on a shared cluster where I have no admin control in terms of RBAC or cluster management.

**Comment by ilya-lesikov** [comment]
Currently we didn't try to make werf work in a namespaced, isolated mode, but we were planning to look into it.

**Comment by ilya-lesikov** [comment]
Werf will only require `get` privilege for the release namespace since 2.6.0: #6198
