### ISSUE TITLE
werf cleanup method not allowed in gitlab even with personal token with api permission

### ISSUE THREAD

**Issue by abrekhov** [werf/werf#4672]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Version

v1.2.122+fix2

### How to reproduce

I am using werf with kubernetes executor in GItlab CI pipeline.

This job is failing:

```yaml
cleanup:
  stage: cleanup
  image: registry.werf.io/werf/werf
  variables:
    WERF_SYNCHRONIZATION: kubernetes://gitlab-ci
  script:
    - source $(werf ci-env gitlab --as-file)
    - export 
    - werf cr login -u nobody -p $WERF_IMAGES_CLEANUP_PASSWORD $WERF_REPO
    - werf cleanup --repo=$CI_REGISTRY_IMAGE
  tags: ["werf"]
```
WERF_IMAGES_CLEANUP_PASSWORD is group variable with value of personal token with API permission (must be enough as said [here](https://werf.io/documentation/v1.2/advanced/ci_cd/gitlab_ci_cd.html#cleaning-up-images).

### Result

$ werf cleanup --repo=$CI_REGISTRY_IMAGE
Version: v1.2.122+fix2
Using project dir: /builds/mks/my-app-werf
Using werf config render file: /tmp/werf-config-render-1689508829
Syncing origin branches and tags
00:02
┌ Syncing origin branches and tags
└ Syncing origin branches and tags (1.15 seconds)
Fetching manifests and metadata
00:00
┌ Fetching manifests and metadata
└ Fetching manifests and metadata (0.20 seconds)
Getting deployed docker images (context inClusterContext) ...
 (0.86 seconds)
Skipping repo tags that are being used in Kubernetes
00:00
┌ Skipping repo tags that are being used in Kubernetes
│   tag: 33fe1ecb1a454ad1b0f134722b1fc9e01d0ad8ee99bd992014f6f95d-1658859622398
└ Skipping repo tags that are being used in Kubernetes (0.00 seconds)
Skipping final repo tags that are being used in Kubernetes
00:00
┌ Skipping final repo tags that are being used in Kubernetes
└ Skipping final repo tags that are being used in Kubernetes (0.00 seconds)
Git history-based cleanup
00:00
┌ Git history-based cleanup
│ ┌ Preparing references to scan
│ │ ┌ references={tag=.* limit={last=10}}
│ │ │ v0.0.1
│ │ └ references={tag=.* limit={last=10}}
│ │ 
│ │ ┌ references={branch=.* limit={in=168h0m0s last=10 operator=And}} imagesPerReference={in=168h0m0s last=2 operator=And}
│ │ │ origin/main
│ │ └ references={branch=.* limit={in=168h0m0s last=10 operator=And}} imagesPerReference={in=168h0m0s last=2 operator=And}
│ │ 
│ │ ┌ references={branch=^(main|master|staging|production)$} imagesPerReference={last=10}
│ │ │ origin/main
│ │ └ references={branch=^(main|master|staging|production)$} imagesPerReference={last=10}
│ └ Preparing references to scan (0.01 seconds)
│ 
│ ┌ ⛵ image my_app_werf
│ │ 
│ │ Tag                                                                     Commits                                   
│ │ 33fe1ecb1a454ad1b0f134722b1fc9e01d0ad8ee99bd992014f6f95d-1658859622398  7f543a183c97e457a97345fd5e63ed98c7[199](https://gitlab.com/mks/my-app-werf/-/jobs/1151#L199)ac2  
│ │                                                                         eb3053322a15aa3330ef76cf65044f1cce5b973d  
│ │                                                                         6468efcbcae805b879e503e20210a3504bb59ffe  
│ │ 
│ │ ┌ Scanning git references history
│ │ └ Scanning git references history (0.00 seconds)
│ │ 
│ │ ┌ Saved tags
│ │ │   tag: 33fe1ecb1a454ad1b0f134722b1fc9e01d0ad8ee99bd99[201](https://gitlab.com/mks/my-app-werf/-/jobs/1151#L201)4f6f95d-1658859622398
│ │ └ Saved tags
│ │ 
│ │ ┌ Cleaning image metadata
│ │ │ ┌ Cleaning up metadata (2/3)
│ │ │ └ Cleaning up metadata (2/3) (0.28 seconds) FAILED
│ │ └ Cleaning image metadata (0.28 seconds) FAILED
│ └ ⛵ image my_app_werf (0.28 seconds) FAILED
└ Git history-based cleanup (0.30 seconds) FAILED
Running time 2.96 seconds
Error: unable to remove repo image meta-ec9d24fe_6468efcbcae805b879e503e[202](https://gitlab.com/mks/my-app-werf/-/jobs/1151#L202)10a3504bb59ffe_33fe1ecb1a454ad1b0f134722b1fc9e01d0ad8ee99bd992014f6f95d-16588596[223](https://gitlab.com/mks/my-app-werf/-/jobs/1151#L223)98: unrecognized status code during DELETE: 405 Method Not Allowed; {"errors":[{"code":"UNSUPPORTED","message":"The operation is unsupported."}]}
Cleaning up project directory and file based variables

### Expected result

There must be no error. Deleting of unused tags must be without an error.

**Comment by alexey-igrychev** [comment]
This error is not related to the token you use. Your registry does not support the delete method, and you should check your configuration.

**Comment by abrekhov** [comment]
> This error is not related to the token you use. Your registry does not support the delete method, and you should check your configuration.

Yeah. You were right. I have added `REGISTRY_STORAGE_DELETE_ENABLED: "true"` to my docker compose as advised here https://github.com/distribution/distribution/issues/1573. And now it's ok. 

Thank you.
