### ISSUE TITLE
Werf wont rebuild images

### ISSUE THREAD

**Issue by onegreyonewhite** [werf/werf#4674]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Version

1.2.122+fix2

### How to reproduce

1. Add new build arg to Dockerfiles.
2. Allow use env variables from CI.
3. Setup CI_COMMIT_SHA from env to new build arg.
4. Run build... no profit.

https://gitlab.com/vstconsulting/images/-/compare/7e15e15ad604d101063fc1719cce1c3ba2adbc6c...master?from_project_id=35926108

### Result

`Use cache image for ...` on each image.

### Expected result

`Building stage...` on each affected images.

### Additional information

[raw_build_output.txt](https://github.com/werf/werf/files/9204797/raw_build_output.txt)

Used docker host for builds instead of buildah.

**Comment by alexey-igrychev** [comment]
Globally scoped ARGs have not any effect if not used in FROM instructions (https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact).

You can use ARG inside certain Dockerfile stage to get the necessary rebuilds:
```
FROM centos:centos7
ARG CI_COMMIT_SHA
```

**Comment by onegreyonewhite** [comment]
@alexey-igrychev thanx. My bad.
