### ISSUE TITLE
Add support to add files from remote git in werf.yam

### ISSUE THREAD

**Issue by CRASH-Tech** [werf/werf#4949]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Problem

In my case I have many projects with identical .helm/ and Dockerfile.
Will be good if I can set url for repo with this files, and werf  automatically adds it to my worktree on a build stage, and remove after.

**Comment by alexey-igrychev** [comment]
At the moment, as a best practice, we recommend using submodules that fit perfectly into giterminism and the delivery process remains reliable and reproducible. Otherwise, you can put the configuration on your own before using werf.

**Comment by alexey-igrychev** [comment]
rel #4948
