### ISSUE TITLE
Print deprecation error when werf-run command used with buildah backend

### ISSUE THREAD

**Issue by distorhead** [werf/werf#4985]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Problem

Currently when buildah backend is enabled `werf run` panics like follows:

```
panic: context is not bound with docker cli
goroutine 1 [running]:
[github.com/werf/werf/pkg/docker.cli({0x3ccb700](http://github.com/werf/werf/pkg/docker.cli(%7B0x3ccb700), 0xc00049c960})
    /git/pkg/docker/main.go:128 +0xb2
...
```

This is because `werf run` was not implemented for buildah backend, nor planned to be implemented.

### Solution (if you have one)

Print deprecation error for user instead of panic, which should call user to use `werf kube-run` instead of `werf run`.

**Comment by ilya-lesikov** [comment]
Solved:
```shell
❯ WERF_BUILDAH_MODE=auto werf run --shell                                                 
Error: command "werf run" is not implemented for Buildah mode
```
