### ISSUE TITLE
Werf for Selectel CRaaS version 3

### ISSUE THREAD

**Issue by gyrter** [werf/werf#5143]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Problem

Api methods was updated before CRaaS public release. We need to update our code.

### Solution (if you have one)

Update API methods

### Additional information

[CRaaS API Docs](https://developers.selectel.ru/docs/selectel-cloud-platform/craas_api/)

**Comment by alexey-igrychev** [comment]
Currently, working with Selectel CRaaS does not require any special actions from the user; it is sufficient to use a token with the necessary set of permissions for cleaning.
