### ISSUE TITLE
GitLab registry "manifest unknown" causing crushes during build and cleanup

### ISSUE THREAD

**Issue by gelangollas** [werf/werf#5185]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Version

1.2.93

### How to reproduce

Problem eventually happening in any projects on werf 1.2. Example of issue for one project:

Environment:
  - Linux kernel 3.10.0-1160.71.1.el7.x86_64
  - CentOS Linux release 7.9.2009 (Core)
  - Docker version 19.03.15, build 99e3ed8919
  - GitLab Community Edition 14.9.5
  - werf 1.2.93
 
Configuration:
  - werf.yaml https://gist.github.com/gelangollas/30289032750a99fed9d635d660205a27
  - using mounts and custom tags

### Result

Dont know how to reproduce. Problem seems to be with werf 1.2 projects only, no similar issues were found with werf 1.1 or with pure docker or kaniko builds. Here is the history of pipelines in order (no changes were made in werf.yaml of stage dependencies):
1. cleanup OK https://gist.github.com/gelangollas/b30727defe34ded5e9d3c0c282c31a6c
2. build OK but tags crushed (registry search by commit custom tag) https://gist.github.com/gelangollas/2c3e9dfdcf72b65dc9cc59f5244fef80 ![image](https://user-images.githubusercontent.com/22047108/209117854-d47bcceb-2c9b-403d-a7b8-e7613ceeb267.png) 
![image](https://user-images.githubusercontent.com/22047108/209118178-64c4bf92-5fe1-4709-8115-3cc39ff98a6e.png)
3. build OK but tags partially crushed for this commit https://gist.github.com/gelangollas/cb9974c8ee2774059bb575e45995e415
4. build OK but tags partially crushed for this commit https://gist.github.com/gelangollas/3543f37157f36ac635ae955820ec115c
5. build crushed because of MANIFEST_UNKNOWN. tags are not crushed but missing custom tags https://gist.github.com/gelangollas/14f5c60a1a6a1bd7f8e0e0a6ac897f4c
6. same as previous https://gist.github.com/gelangollas/0f6c32a122e5b7a33d5fe38f8cbdc199
7. same as previous https://gist.github.com/gelangollas/c410512a8b24cb51470be7e24b05d1d6
8. cleanup crushed https://gist.github.com/gelangollas/26ea91b31c9d99bd64ca25c85d5deb81
9. build in completely separate brunch OK (should not be affecting next build) https://gist.github.com/gelangollas/056ab68dc049a2dc1be6f8ffd308efc6
10. build OK https://gist.github.com/gelangollas/e07030877b16bae9a32cd10e63f487d0
next builds are completely fine and all next cleanups are crushing just like №8
 

### Expected result

No crushed tags in GitLab container registry

**Comment by alexey-igrychev** [comment]
Hi @gelangollas, and thank you for your feedback.

The area of responsibility of werf cleanup is the removal of image tags (manifests), and the direct removal of related data is performed by the container registry garbage collector (GC).

When calling the garbage collector, the container registry must be set to the read-only mode or turned off completely. Otherwise, it is highly probable that the images published during the procedure will not be considered by the garbage collector and **will be corrupted**.

You can read more about the garbage collector and how to use it in the documentation:
1. [Docker Registry GC](https://docs.docker.com/registry/garbage-collection/#more-details-about-garbage-collection)
2. [GitLab CR GC](https://docs.gitlab.com/ee/administration/packages/container_registry.html#container-registry-garbage-collection).

**Comment by gelangollas** [comment]
Hi @alexey-igrychev! Thanks for the reply. 
If I understand you correctly, probable cause of corrupted tags is publishing stages to remote registry during cleanup or `werf build` during `werf cleanup` if in terms of CI/CD (and we don't use any other staff to deal with registry). That makes perfect sense and I checked some of our projects which has cleanup issues. But I found no correlation for corrupted tags between builds and cleanups. It just doesn't happen at the same time. There is at least a couple of hours between build and cleanup.

If `werf cleanup` command finished successfully, then GC also finished?
Is werf restraining cleanup during building images to the same remote registry if synchronization server configured as local?

**Comment by alexey-igrychev** [comment]
> If I understand you correctly, probable cause of corrupted tags is publishing stages to remote registry during cleanup or werf build during werf cleanup

No. werf cannot corrupt images in the container registry, and you can run any commands simultaneously without any issues. 

Most likely, the problem has nothing to do with werf, and you'll need to see how you've set up the GC for your container registry (maybe it starts automatically).

**Comment by gelangollas** [comment]
Probably found the cause of currupted tags. Those tags were created during the time of executing `werf host cleanup` (for werf 1.1 and werf 1.2):

 $ crontab -l | grep 'host cleanup'
0 5 * * * werf-1.2 host cleanup --home-dir=/home/gitlab-runner/.werf_v12 --allowed-local-cache-volume-usage=80 --allowed-docker-storage-volume-usage=80
0 5 * * * werf host cleanup --home-dir=/home/gitlab-runner/.werf

**Comment by alexey-igrychev** [comment]
I see an inconsistency in the fact that you have corrupted images in the container registry and werf host cleanup is doing host cleanup. You should look for the problem in the parallel running of GC.

**Comment by gelangollas** [comment]
Seems like you are right. Recent events showed me that werf is not the thing that causing crushed tags. Will be searching problem in Gitlab GC
