### ISSUE TITLE
Dependency update command or option with proper caching

### ISSUE THREAD

**Issue by distorhead** [werf/werf#5255]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Problem

The problems with `werf helm dependency update .helm` and local development:

1. It creates excess `.helm/charts` directory with downloaded charts, but these charts should not be stored in the git repo. This creates difficulties with understanding of the right flow of subcharts usage.
2. It does not fills werf's cache of downloaded charts which reside in `~/.werf/local_cache/helm_chart_dependencies/...`. And after calling `werf helm dependency update` during local development, subsequent call to any highlevel werf command will download needed charts again.

### Solution (if you have one)

There should be either an option for `werf helm dependency update .helm --with-cache` or a special command like `werf dependencies update`, which would not create `.helm/charts` folder,  which would download charts into the proper cache dir into `~/.werf/local_cache/helm_chart_dependencies`, which would update `.helm/Chart.lock` file as usual. This change would drastically support natural flow of werf usage.

**Comment by alexey-igrychev** [comment]
solved https://github.com/werf/werf/pull/5316
