### ISSUE TITLE
Add "diff" func

### ISSUE THREAD

**Issue by CRASH-Tech** [werf/werf#5334]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Problem

subj

**Comment by distorhead** [comment]
Diff functionality is certainly a planned feature of our new deploy engine. More info: https://github.com/werf/werf/issues/5639.

**Comment by ilya-lesikov** [comment]
Done in werf v2 as `werf plan` command.
