### ISSUE TITLE
Add warning note in docs about forbidden using `mount` feature for dockerfile-based images

### ISSUE THREAD

**Issue by andrew-demb** [werf/werf#5545]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Problem

While trying to add a mount to build dockerfile-based image process I get an error from werf. An error was not clear about possible solution and reasons (because short search in docs doesn't make it clear that there is any typo or not available to be used key)

```
werf build      
Version: v1.2.214+fix3
Using werf config render file: /tmp/werf-config-render-3672032314
Running time 0.04 seconds
Error: unable to load werf config: unknown fields: `mount`!

/tmp/werf-config-render-3672032314

     4  image: ~
     5  dockerfile: Dockerfile
     6  mount:
     7  - from: build_dir
     8    to: /mount
```

### Solution (if you have one)

Provide details about forbidden to be used `mount` directive for dockerfile-based images in error/docs.

### Additional information

Docs:
- https://werf.io/documentation/v1.2/usage/build/stapel/mounts.html
- https://werf.io/documentation/v1.2/reference/werf_yaml.html

**Comment by alexey-igrychev** [comment]
The mount directive is related to the stapel image configuration and you cannot use it for Dockerfile images, as evidenced by the error and the related documentation pages (e.g. [werf.yaml reference](https://werf.io/documentation/v1.2/reference/werf_yaml.html#L104)).

Thanks for the feedback.

**Comment by andrew-demb** [comment]
I'm ok to close the issue then.
Thanks.
