### ISSUE TITLE
Upgrading 1.1 -> 1.2 docs can suggest a new way of specifying custom image tags

### ISSUE THREAD

**Issue by andrew-demb** [werf/werf#5555]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Problem

https://werf.io/documentation/v1.2/resources/how_to_migrate_from_v1_1_to_v1_2.html#interface-rework

> There is no more --tag-by-stages-signature, --tag-git-branch, --tag-git-commit, --tag-git-tag, --tag-custom options, --tag-by-stages-signature behaviour is default.
> Forcing of custom tags is [not yet available](https://github.com/werf/werf/issues/2869) in the v1.2

https://github.com/werf/werf/issues/2869 is already resolved.

### Solution (if you have one)

Upgrading docs can be updated according to provided feature to use custom tagging.

### Additional information

https://github.com/werf/werf/releases/tag/v1.2.28

**Comment by alexey-igrychev** [comment]
Version 1.1 is no longer supported (only critical cases), so the article may differ from the current functionality. We have tried to change the structure of the 1.2 documentation so that the search for solutions to such issues does not take much time. 

In any case, thanks for the feedback ❤️
