### ISSUE TITLE
Add support registries.conf

### ISSUE THREAD

**Issue by NikolaBoyko** [werf/werf#5773]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Problem

Now we can't set mirrors for registries.

### Solution (if you have one)

Add support registries.conf. It prevent problems with rate limit for docker.io api

**Comment by alexey-igrychev** [comment]
rel #5977

**Comment by ilya-lesikov** [comment]
Implemented in v2.4.0 and v1.2.314: https://werf.io/docs/latest/usage/build/process.html#container-registry-mirrors
