### ISSUE TITLE
buildah: using aws assumed role results in ignoring ECR account via --repo

### ISSUE THREAD

**Issue by alexremn** [werf/werf#5839]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Version

v1.2.267

### How to reproduce

1. Use buiildah on linux;
2. Use GH Actions runners on EKS under AWS IRSA;
3. Try to issue werf cleanup with specified repo deployed in another account.

### Result

Werf will use account id for ECR url from assumed role, not from --repo.

### Expected result

Werf will use ECR repo from --repo.

**Comment by alexey-igrychev** [comment]
Hi, @alexremn, and thank you for the issue report. 

To better understand your case, could you provide the options used with the `werf cleanup` command? Also, have you checked our documentation [here](https://werf.io/documentation/v1.2/usage/cleanup/cr_cleanup.html#aws-ecr)? It might contain relevant information.
