### ISSUE TITLE
Добавить опции в режим деплоя bundle apply

### ISSUE THREAD

**Issue by sgolod** [werf/werf#5968]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Problem

Начиная с версии 1.2 werf поддерживает два режима деплоя:
- `werf converge ...` ("непрерывная" доставка с контролем изменений в git)
- `werf bundle apply` (деплой ранее опубликованного релиза)

В режиме `werf bundle apply` отсутствуют опции, имеющиеся в режиме `converge`:
1. `--atomic (--auto-rollback)`
2. `--timeout`
3. `--skip-dependencies-repo-refresh`

### Solution (if you have one)

Предлагаю добавить данные опции для совместимости всех режимов деплоя и совместимости с деплоем через helm upgrade (`--atomic, --timeout`)

**Comment by ilya-lesikov** [comment]
Will be added in 1.2.292
