### ISSUE TITLE
Comprehensive support for mirror container registries

### ISSUE THREAD

**Issue by alexey-igrychev** [werf/werf#5977]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Problem

Currently, users can utilize mirror container registries by configuring the Docker daemon. However, equivalent functionality is lacking for the Buildah backend, limiting flexibility and efficiency in registry management.

### Solution (if you have one)

Support for mirrors in werf should be done on two levels: when interacting with the container registry via API, and for the build backend directly at build time. 

In the case of the Docker backend, the configuration is not werf's responsibility and the user needs to configure mirrors and restart the daemon him/herself. With Buildah the story is different — it is fully compiled into werf and all its configuration is created by werf in the process. 

To solve the issue we suggest adding support for `--container-registry-mirror` option and using it when **_initializing API_** and **_Buildah backend_**. 

**Initializing API**

The current support in the API is as follows: 

https://github.com/werf/werf/blob/b2a60225a4f8d06429eb57cc3fb8b3a34e2addd3/pkg/docker_registry/generic_api.go#L125-L148

For the Docker backend, you need to add validation and an error with an instruction if the specified mirrors are missing. In case of the Buildah backend, mirrors are simply added as is.

**Initializing Buildah backend**

When initializing the backend, you need to add mirrors to the configuration ([documentation](https://github.com/containers/image/blob/main/docs/containers-registries.conf.5.md#remapping-and-mirroring-registries) and [an example](https://github.com/containers/image/blob/main/docs/containers-registries.conf.5.md#example) are available in the Buildah repository).

https://github.com/werf/werf/blob/00ee0e1d19c3d5511c641c8ab8794d84a6f01655/pkg/buildah/native_linux.go#L114-L117

**Comment by ulascansenturk** [comment]
Hello @alexey-igrychev  I'm interested in contributing to Werf and would like to help with this particular issue. Could you please assign it to me?

**Comment by alexey-igrychev** [comment]
That's great! Feel free to contact me about anything 🙌🏼
