### ISSUE TITLE
werf compose don't receive image variables after 1.2.322

### ISSUE THREAD

**Issue by dmitryuk** [werf/werf#6308]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Version

1.2.322

### How to reproduce

1.2.322 stable - 1.2.325 alpha

### Result

WARN[0000] The "WERF_BACKEND_DOCKER_IMAGE_NAME" variable is not set. Defaulting to a blank string. 

### Expected result

Environment works fine, variables set in docker-compose

### Additional information

After upgrading 1.2.321 to 1.2.322 all environment variables gone in docker-compose

```
services:
    prepare:
        image: "${WERF_BACKEND_DOCKER_IMAGE_NAME}"
```

Error:
```
WARN[0000] The "WERF_BACKEND_DOCKER_IMAGE_NAME" variable is not set. Defaulting to a blank string. 
```

I sure that commit is a cause https://github.com/werf/werf/commit/da7840c76efc698afca5081e50312eaa00e8e8fd

**Comment by alexey-igrychev** [comment]
Thank you for bringing this to our attention.

We have attempted to reproduce the issue but were unable to do so. To help us investigate further, could you please provide a reproducible example of your configuration? Additionally, include the exact command and arguments you are using to run werf.

**Comment by dmitryuk** [comment]
It looks like a trouble is actual than we are using docker-compose service extends functionality. But I use this in tens of projects yet
https://docs.docker.com/compose/multiple-compose-files/extends/

I did an example repo https://github.com/dmitryuk/werf_test to reproduce the issue

**Comment by alexey-igrychev** [comment]
Thanks for the update. The fix is done. 
We’ve reverted to the old working logic in 1.2 stable, and the new logic is in alpha, beta, and ea.
