### ISSUE TITLE
Feature enabling verbose for `werf kubectl get` cli command

### ISSUE THREAD

**Issue by smilingDima** [werf/werf#6319]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Problem

I have problem connecting gitlab to k8s:
`werf coverage`

> Error: release deploy: construct kube client factory: Kubernetes cluster unreachable: error getting kubernetes server version: Get "http://localhost:8080/version": dial tcp [::1]:8080: connect: connection refused 

I'm trying to view more information and enable verbose output.
But `$ werf kubectl get nodes -v=10` returns:

> Error: unknown shorthand flag: 'v' in -v=10
> See 'werf kubectl get --help' for usage.

### Solution (if you have one)

Adding permission to pass -v flag.

**Comment by ilya-lesikov** [comment]
Fixed by https://github.com/werf/werf/pull/6415
