### ISSUE TITLE
Unable to use relative path for `context`

### ISSUE THREAD

**Issue by samuellvicente** [werf/werf#6330]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Version

2.10.5

### How to reproduce

Using this as an example:
https://github.com/werf/first-steps-example

Suppose this tree:

```
├── 001_build
│   ├── Dockerfile
│   ├── hello.sh
│   └── werf.yaml
├── 002-deploy
│   ├── Dockerfile
│   ├── hello.sh
│   └── werf.yaml
```

if we change the 002-deploy werf.yaml to try to build 001_build's Dockerfile :
```
project: werf-first-app
configVersion: 1

---
image: app
dockerfile: Dockerfile
context: ../001_build
```
it does not work

### Result

```
Error: unable to load werf config: `context: PATH` should be relative to project directory!

/tmp/werf-config-render-186646981

     5  image: app
     6  dockerfile: Dockerfile
     7  context: ../001_build
```

### Expected result

The image building

### Additional information

I found an issue https://github.com/werf/werf/issues/5305 with a similar problem but the Dockerfile wasnt inside the context, in this case it is and it does not work

**Comment by alexey-igrychev** [comment]
Hi! This repository was created for an article, and each directory corresponds to a section of that article. The expected steps for users are as follows:

```bash
git clone https://github.com/werf/examples

cp -rf 001_build example

cd example
git init
git add .
git commit -m "Initial commit"

werf build
```

To get started with werf, I recommend following the [guide](https://werf.io/guides/nodejs/100_basic/10_build.html) or trying the simple examples from the [Getting Started](https://werf.io/getting_started/) page. This will help you understand the process and get your project up and running quickly.

Hope this helps!

**Comment by alexey-igrychev** [comment]
To achieve what you were trying to do, you need to use the following configuration:

```yaml
project: werf-first-app
configVersion: 1

---
image: app
dockerfile: Dockerfile
context: 001_build
```

Then, run `werf` from the project root like this:

```bash
werf build --config 002_deploy/werf.yaml
```

However, we do not recommend this approach. Instead, we suggest defining all images directly in a single `werf.yaml` file located at the project root. This approach is cleaner and easier to maintain.
