### ISSUE TITLE
Ansible apt_repository module do not detect debian release name correctly

### ISSUE THREAD

**Issue by distorhead** [werf/werf#635]
For example running following apt_repository in `ubuntu:16.04`:

```
    apt_repository:
      repo: "ppa:ondrej/php"
```

will try to add ppa for debian `sid`.

Fixed for now with explicit codename specification:

```
    apt_repository:
      repo: "ppa:ondrej/php"
      codename: "trusty"
```

The root of the problem is somewhere in dappdeps/ansible.

**Comment by distorhead** [comment]
The usage of apt_repository module is blocked by the issue https://github.com/flant/werf/issues/635

**Comment by alexey-igrychev** [comment]
This issue is being closed because the ansible functionality is no longer being developed or supported. This feature has been deprecated and will be removed in version v3. We recommend using the shell directive instead.
