### ISSUE TITLE
Rendering the application version in the helm chart

### ISSUE THREAD

**Issue by yury-k8** [werf/werf#6390]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Problem

The project maintains the value of the application version. The value can be read from a file in the root of the project. This value must be assigned to the application deployment labels. At the moment, it is possible to set only in Chart.yaml. This option is not useful.

### Solution (if you have one)

It is proposed to make it possible to template Chart.yaml with access to files in the root of the project (not in the Helm folder of the chart) or to set a parameter in templating werf.yaml with subsequent templating of the Deployment manifest.

**Comment by Aleksey-Kalinin** [comment]
Поддерживаю шаблонизацию Chart.yaml и values.yaml, а также доступ из шаблонов к файлам вне проекта Helm

**Comment by drey** [comment]
I'm going to implement this feature, but would prefer to discuss some questions before getting started.

@alexey-igrychev is it handy to be able to read the app version from a dedicated file or it is fine to have it only in the werf.yaml? If reading version from an external file is desired, what file formats should we consider? Basically we can support everything, but a lot of options is not always good. 

With the external version file support I see the following scenarios:

1. Plaint text file. The versions should be at the first line. No special formatting rules.
2. YAML or JSON file. The content is not matter as long as we have a `version` key at the top level. For instance:
```yaml
---
version: "0.0.1"
...
```

**Comment by alexey-igrychev** [comment]
solved
