### ISSUE TITLE
werf converge does not allow to use Gitlab registry

### ISSUE THREAD

**Issue by drey** [werf/werf#6406]
### Before proceeding

- [X] I didn't find a similar [issue](https://github.com/werf/werf/issues)

### Version

2.10.9

### How to reproduce

1. Run `werf converge --help` and see the following section:
```
      --repo-container-registry=''
            Choose repo container registry implementation.
            The following container registries are supported: ecr, acr, default, dockerhub, gcr, github, gitlab, harbor, quay.
            Default $WERF_REPO_CONTAINER_REGISTRY or auto mode (detect container registry by repo address).
```
So, the help says that gitlab is supported, but it is not. 

### Result

There are no additional flags to setup Gitlab registry authentication params for `werf converge` - https://github.com/werf/werf/blob/fc7eb8a0f88d62708da6dcadff4083ee17a5914c/cmd/werf/common/repo_data.go#L135C1-L158C1

### Expected result

It should be possible to setup Gitlab registry authentication params by both env and cli methods as it has been already done for other registry types.

### Additional information

Core Gitlab registry implementation already exists and is in use in other werf components 
(https://github.com/werf/werf/blob/fc7eb8a0f88d62708da6dcadff4083ee17a5914c/pkg/docker_registry/gitlab_registry.go#L19C1-L19C50)

**Comment by Drey** [comment]
After discussion in the official telegram support channel it became clear that the registry credentials don't have to be provided by CLI arguments, as it is enough to have a docker config.json to have werf authenticated with the registry.

So it would make sense to handle this case as a documentation bug.

**Comment by alexey-igrychev** [comment]
Hi again!

Currently, authorization in the container registry can be handled via the `werf ci-env` command if the relevant environment variables for CI container registry authorization are set. You can authorize any container registry with the `werf cr login` command or any other that updates your docker config (e.g., `docker login`). 

Also, the `werf cleanup` and `werf purge` commands may require additional credentials to delete tags using the native container registry API. Other commands do not perform authorization, and the presence of these options is incorrect. We will remove them soon to avoid any confusion for users.
