### ISSUE TITLE
Support RUN --mount=type=secret

### ISSUE THREAD

**Issue by slavb18** [werf/werf#6433]
Hi!

Is there support for secrets mounting in docker (RUN --mount=type=secret) like in docker/build-push-action?

https://render.com/docs/docker-secrets

is it possible to run `docker build --secret` from `werf converge`

``` 
DOCKER_BUILDKIT=1 docker build --secret id=FILENAME,src=LOCAL_FILENAME ...
```

**Comment by alexey-igrychev** [comment]
fixed by https://github.com/werf/werf/pull/6429
